//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockPaperScissorsGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RockPaperScissorsGame.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, my name is morteza farhadi, This game is written only for a chalange code for Mega group Co. that i have designed and implemented the Rock Paper Scissors game.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between [{0}]: {1} and [{2}]: {3} which one is winner?.
        /// </summary>
        public static string BetweenTowItemsWinnerIs {
            get {
                return ResourceManager.GetString("BetweenTowItemsWinnerIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice a number between {0} and {1}.
        /// </summary>
        public static string ChoiceBetweenTwoNumber {
            get {
                return ResourceManager.GetString("ChoiceBetweenTwoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice a currect number.
        /// </summary>
        public static string ChoiceCurrectNumber {
            get {
                return ResourceManager.GetString("ChoiceCurrectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice a number.
        /// </summary>
        public static string ChoiceNumber {
            get {
                return ResourceManager.GetString("ChoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ════ Equal result ════.
        /// </summary>
        public static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure  to exit? (Y/N).
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}]: {1}.
        /// </summary>
        public static string GameItem {
            get {
                return ResourceManager.GetString("GameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game max level?.
        /// </summary>
        public static string GameMaxLevel {
            get {
                return ResourceManager.GetString("GameMaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You: {0}       Sys: {1}.
        /// </summary>
        public static string GameResult {
            get {
                return ResourceManager.GetString("GameResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between {0} and  {1} winner is =&gt; {2}.
        /// </summary>
        public static string ItemActionResult {
            get {
                return ResourceManager.GetString("ItemActionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, You lost ;-(.
        /// </summary>
        public static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleas type currect number of menu items.
        /// </summary>
        public static string TypeCorrectNumberOfMenu {
            get {
                return ResourceManager.GetString("TypeCorrectNumberOfMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleas type a currect number.
        /// </summary>
        public static string TypeCurrectNumber {
            get {
                return ResourceManager.GetString("TypeCurrectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type you&apos;r new game Item.
        /// </summary>
        public static string TypeNewGameItem {
            get {
                return ResourceManager.GetString("TypeNewGameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, You won ;-).
        /// </summary>
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ══════ You lost ══════.
        /// </summary>
        public static string YouLost {
            get {
                return ResourceManager.GetString("YouLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;r choice number is ({0}) and system choice number is({1}).
        /// </summary>
        public static string YouNumberSysNumber {
            get {
                return ResourceManager.GetString("YouNumberSysNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ══════ You won ══════.
        /// </summary>
        public static string YouWon {
            get {
                return ResourceManager.GetString("YouWon", resourceCulture);
            }
        }
    }
}
